spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/order?useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&autoReconnection=true&serverTimezone=Asia/Seoul
    username: sausage
    password: sausage

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: ALWAYS

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

kafka:
  address: localhost:9092,localhost:9093,localhost:9094
  group:
    name: ord-service
  topic:
    cart-share-service.cart-share-item-list.deleting: cart-share-service.cart-share-item-list.deleting
    cart-share-service.cart-share-edit-psbl-yn.updating: cart-share-service.cart-share-edit-psbl-yn.updating
    cart-share-ord-service.cal-st-yn.updating: cart-share-ord-service.cal-st-yn.updating